# DD/MM/YYYY - description
OUTDIR: /path/to/output
READS_DIR_RAW: /path/to/RAW reads/ # don't add the reads files, just the directory where they are. Reads before QC
READS_DIR: /path/to/cleaned reads/ # DIR to safe cleaned reads 
ASSEMBLY: /path/to/assembly
PREFIX: <output name>
